import { IChampion } from "../../App";

export const champions: IChampion[] = [
  {
    id: "Aatrox",
    name: "Aatrox",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aatrox_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Aatrox.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Ex-Humano"],
    resource: "Nenhum",
    range_type: ["Corpo a Corpo"],
    regions: ["Shurima"],
    release_year: 2013,
  },
  {
    id: "Ahri",
    name: "Ahri",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Ahri.png",
    },
    roles: ["Mid"],
    tags: ["Mago", "Assassino"],
    genre: "Feminino",
    specie: ["Vastaya"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ionia"],
    release_year: 2011,
  },
  {
    id: "Akali",
    name: "Akali",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akali_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Akali.png",
    },
    roles: ["Mid", "Top"],
    tags: ["Assassino"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Energia",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2010,
  },
  {
    id: "Akshan",
    name: "Akshan",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akshan_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Akshan.png",
    },
    roles: ["Mid", "Top"],
    tags: ["Atirador", "Assassino"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Shurima"],
    release_year: 2021,
  },
  {
    id: "Alistar",
    name: "Alistar",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Alistar_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Alistar.png",
    },
    roles: ["Suporte"],
    tags: ["Tanque", "Suporte"],
    genre: "Masculino",
    specie: ["Minotauro"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Runeterra"],
    release_year: 2009,
  },
  {
    id: "Amumu",
    name: "Amumu",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Amumu_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Amumu.png",
    },
    roles: ["Selva", "Suporte"],
    tags: ["Tanque", "Mago"],
    genre: "Masculino",
    specie: ["Morto-Vivo", "Yordle"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Shurima"],
    release_year: 2009,
  },
  {
    id: "Anivia",
    name: "Anivia",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Anivia_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Anivia.png",
    },
    roles: ["Mid"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Deus", "Espírito"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Freljord"],
    release_year: 2009,
  },
  {
    id: "Annie",
    name: "Annie",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Annie_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Annie.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Feminino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Noxus", "Runeterra"],
    release_year: 2009,
  },
  {
    id: "Aphelios",
    name: "Aphelios",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aphelios_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Aphelios.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Masculino",
    specie: ["Humano", "Espiritualista"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Targon"],
    release_year: 2019,
  },
  {
    id: "Ashe",
    name: "Ashe",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ashe_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Ashe.png",
    },
    roles: ["Atirador", "Suporte"],
    tags: ["Atirador", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Nascido do Gelo"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Freljord"],
    release_year: 2009,
  },
  {
    id: "Aurelion Sol",
    name: "Aurelion Sol",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/AurelionSol_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/AurelionSol.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Masculino",
    specie: ["Celestial", "Dragão"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Shurima"],
    release_year: 2014,
  },
  {
    id: "Azir",
    name: "Azir",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Azir_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Azir.png",
    },
    roles: ["Mid"],
    tags: ["Atirador", "Mago"],
    genre: "Masculino",
    specie: ["Deus-Guerreiro"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Shurima"],
    release_year: 2014,
  },
  {
    id: "Bardo",
    name: "Bardo",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Bard_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Bard.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Masculino",
    specie: ["Celestial"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Runeterra"],
    release_year: 2015,
  },
  {
    id: "Bel'Velth",
    name: "Bel'Velth",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Belveth_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Belveth.png",
    },
    roles: ["Selva"],
    tags: ["Lutador"],
    genre: "Feminino",
    specie: ["Ser Vazio"],
    resource: "Nenhum",
    range_type: ["Corpo a Corpo"],
    regions: ["Vazio"],
    release_year: 2013,
  },
  {
    id: "Blitzcrank",
    name: "Blitzcrank",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Blitzcrank_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Blitzcrank.png",
    },
    roles: ["Suporte"],
    tags: ["Lutador", "Tanque"],
    genre: "Outro",
    specie: ["Golem"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Zaun"],
    release_year: 2009,
  },
  {
    id: "Brand",
    name: "Brand",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Brand_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Brand.png",
    },
    roles: ["Top"],
    tags: ["Mago"],
    genre: "Masculino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Runeterra"],
    release_year: 2011,
  },
  {
    id: "Braum",
    name: "Braum",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Braum_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Braum.png",
    },
    roles: ["Suporte"],
    tags: ["Tanque", "Suporte"],
    genre: "Masculino",
    specie: ["Humano", "Nascido do Gelo"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Freljord"],
    release_year: 2014,
  },
  {
    id: "Caitlyn",
    name: "Caitlyn",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Caitlyn_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Caitlyn.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Piltover"],
    release_year: 2011,
  },
  {
    id: "Camille",
    name: "Camille",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Camille_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Camille.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Feminino",
    specie: ["Humano", "Ciborgue"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Piltover"],
    release_year: 2016,
  },
  {
    id: "Cassiopeia",
    name: "Cassiopeia",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Cassiopeia_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Cassiopeia.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Feminino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Noxus", "Shurima"],
    release_year: 2010,
  },
  {
    id: "Cho'Gath",
    name: "Cho'Gath",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Chogath_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Chogath.png",
    },
    roles: ["Top"],
    tags: ["Tanque", "Mago"],
    genre: "Masculino",
    specie: ["Ser Vazio"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Vazio"],
    release_year: 2009,
  },
  {
    id: "Corki",
    name: "Corki",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Corki_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Corki.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Masculino",
    specie: ["Yordle"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Bandópolis"],
    release_year: 2009,
  },
  {
    id: "Darius",
    name: "Darius",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Darius_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Darius.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Noxus"],
    release_year: 2012,
  },
  {
    id: "Diana",
    name: "Diana",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Diana_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Diana.png",
    },
    roles: ["Mid", "Selva"],
    tags: ["Mago", "Lutador"],
    genre: "Feminino",
    specie: ["Humano", "Aspecto"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Targon"],
    release_year: 2012,
  },
  {
    id: "Dr.Mundo",
    name: "Dr.Mundo",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/DrMundo_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/DrMundo.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano", "Quimicamente Alterado"],
    resource: "Vida",
    range_type: ["Corpo a Corpo"],
    regions: ["Zaun"],
    release_year: 2009,
  },
  {
    id: "Draven",
    name: "Draven",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Draven_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Draven.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Noxus"],
    release_year: 2012,
  },
  {
    id: "Ekko",
    name: "Ekko",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ekko_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Ekko.png",
    },
    roles: ["Mid", "Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Zaun"],
    release_year: 2015,
  },
  {
    id: "Elise",
    name: "Elise",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Elise_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Elise.png",
    },
    roles: ["Selva"],
    tags: ["Mago", "Lutador"],
    genre: "Feminino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["Corpo a Corpo", "À distância"],
    regions: ["Noxus", "Ilha das Sombras"],
    release_year: 2012,
  },
  {
    id: "Evelynn",
    name: "Evelynn",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Evelynn_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Evelynn.png",
    },
    roles: ["Selva"],
    tags: ["Mago", "Assassino"],
    genre: "Feminino",
    specie: ["Demônio", "Espírito"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Runeterra"],
    release_year: 2009,
  },
  {
    id: "Ezreal",
    name: "Ezreal",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ezreal_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Ezreal.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador", "Mago"],
    genre: "Masculino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Piltover"],
    release_year: 2010,
  },
  {
    id: "Fiddlesticks",
    name: "Fiddlesticks",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Fiddlesticks.png",
    },
    roles: ["Selva"],
    tags: ["Mago", "Suporte"],
    genre: "Outro",
    specie: ["Demônio", "Espírito"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Runeterra"],
    release_year: 2009,
  },
  {
    id: "Fiora",
    name: "Fiora",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiora_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Fiora.png",
    },
    roles: ["Top"],
    tags: ["Assassino", "Lutador"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Demacia"],
    release_year: 2012,
  },
  {
    id: "Fizz",
    name: "Fizz",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fizz_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Fizz.png",
    },
    roles: ["Mid"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Yordle"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Águas de Sentina"],
    release_year: 2011,
  },
  {
    id: "Galio",
    name: "Galio",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Galio_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Galio.png",
    },
    roles: ["Mid", "Suporte"],
    tags: ["Tanque", "Mago"],
    genre: "Masculino",
    specie: ["Golem"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Demacia"],
    release_year: 2010,
  },
  {
    id: "Gangplank",
    name: "Gangplank",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gangplank_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Gangplank.png",
    },
    roles: ["Mid", "Top"],
    tags: ["Lutador"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Águas de Sentina"],
    release_year: 2009,
  },
  {
    id: "Garen",
    name: "Garen",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Garen_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Garen.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Nenhum",
    range_type: ["Corpo a Corpo"],
    regions: ["Demacia"],
    release_year: 2010,
  },
  {
    id: "Gnar",
    name: "Gnar",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gnar_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Gnar.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Yordle"],
    resource: "Fúria",
    range_type: ["Corpo a Corpo", "À distância"],
    regions: ["Freljord"],
    release_year: 2014,
  },
  {
    id: "Gragas",
    name: "Gragas",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gragas_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Gragas.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Mago", "Lutador"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Freljord"],
    release_year: 2010,
  },
  {
    id: "Graves",
    name: "Graves",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Graves_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Graves.png",
    },
    roles: ["Selva"],
    tags: ["Atirador"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Águas de Sentina"],
    release_year: 2011,
  },
  {
    id: "Gwen",
    name: "Gwen",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gwen_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Gwen.png",
    },
    roles: ["Mid"],
    tags: ["Assassino", "Lutador"],
    genre: "Feminino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Camaveia", "Ilha das Sombras"],
    release_year: 2013,
  },
  {
    id: "Hecarim",
    name: "Hecarim",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Hecarim_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Hecarim.png",
    },
    roles: ["Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Morto-Vivo"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Camaveia", "Ilha das Sombras"],
    release_year: 2013,
  },
  {
    id: "Heimerdinger",
    name: "Heimerdinger",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Heimerdinger_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Heimerdinger.png",
    },
    roles: ["Mid", "Top"],
    tags: ["Mago", "Suporte"],
    genre: "Masculino",
    specie: ["Yordle"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Piltover"],
    release_year: 2009,
  },
  {
    id: "Illaoi",
    name: "Illaoi",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Illaoi_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Illaoi.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Feminino",
    specie: ["Humano", "Espiritualista"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Águas de Sentina"],
    release_year: 2015,
  },
  {
    id: "Irelia",
    name: "Irelia",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Irelia_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Irelia.png",
    },
    roles: ["Mid", "Top"],
    tags: ["Assassino", "Lutador"],
    genre: "Feminino",
    specie: ["Humano", "Espiritualista"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2010,
  },
  {
    id: "Ivern",
    name: "Ivern",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ivern_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Ivern.png",
    },
    roles: ["Selva"],
    tags: ["Mago", "Suporte"],
    genre: "Masculino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Freljord", "Ionia"],
    release_year: 2016,
  },
  {
    id: "Janna",
    name: "Janna",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Janna_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Janna.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Deus", "Espírito"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Shurima", "Zaun"],
    release_year: 2009,
  },
  {
    id: "Jarvan IV",
    name: "Jarvan IV",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/JarvanIV_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/JarvanIV.png",
    },
    roles: ["Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Demacia"],
    release_year: 2011,
  },
  {
    id: "Jax",
    name: "Jax",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jax_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Jax.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Desconhecido"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Icathia", "Runeterra", "Shurima"],
    release_year: 2009,
  },
  {
    id: "Jayce",
    name: "Jayce",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jayce_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Jayce.png",
    },
    roles: ["Mid", "Top"],
    tags: ["Lutador", "Atirador"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["Corpo a Corpo", "À distância"],
    regions: ["Piltover"],
    release_year: 2012,
  },
  {
    id: "Jhin",
    name: "Jhin",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jhin_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Jhin.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Masculino",
    specie: ["Humano", "Espiritualista"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ionia"],
    release_year: 2016,
  },
  {
    id: "Jinx",
    name: "Jinx",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Jinx.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Feminino",
    specie: ["Humano", "Quimicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Zaun"],
    release_year: 2013,
  },
  {
    id: "Kai'Sa",
    name: "Kai'Sa",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kaisa_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Kaisa.png",
    },
    roles: ["Mid", "Atirador"],
    tags: ["Atirador"],
    genre: "Feminino",
    specie: ["Humano", "Ser Vazio"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Shurima", "Vazio"],
    release_year: 2018,
  },
  {
    id: "Kalista",
    name: "Kalista",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kalista_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Kalista.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Feminino",
    specie: ["Morto-Vivo"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Camaveia", "Ilha das Sombras"],
    release_year: 2014,
  },
  {
    id: "Karma",
    name: "Karma",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Karma_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Karma.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Espiritualista"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ionia"],
    release_year: 2011,
  },
  {
    id: "Karthus",
    name: "Karthus",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Karthus_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Karthus.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Masculino",
    specie: ["Morto-Vivo"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Noxus", "Ilha das Sombras"],
    release_year: 2009,
  },
  {
    id: "Kassadin",
    name: "Kassadin",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kassadin_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Kassadin.png",
    },
    roles: ["Mid"],
    tags: ["Mago", "Assassino"],
    genre: "Masculino",
    specie: ["Humano", "Ser Vazio"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Shurima", "Vazio"],
    release_year: 2009,
  },
  {
    id: "Katarina",
    name: "Katarina",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Katarina_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Katarina.png",
    },
    roles: ["Mid"],
    tags: ["Mago", "Assassino"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Nenhum",
    range_type: ["Corpo a Corpo"],
    regions: ["Noxus"],
    release_year: 2009,
  },
  {
    id: "Kayle",
    name: "Kayle",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayle_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Kayle.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Aspecto", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["Corpo a Corpo", "À distância"],
    regions: ["Demacia", "Targon"],
    release_year: 2009,
  },
  {
    id: "Kayn",
    name: "Kayn",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayn_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Kayn.png",
    },
    roles: ["Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Humano", "Darkin", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia", "Noxus", "Runeterra", "Shurima"],
    release_year: 2017,
  },
  {
    id: "Kennen",
    name: "Kennen",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kennen_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Kennen.png",
    },
    roles: ["Top"],
    tags: ["Atirador", "Mago"],
    genre: "Masculino",
    specie: ["Yordle"],
    resource: "Energia",
    range_type: ["À distância"],
    regions: ["Ionia"],
    release_year: 2010,
  },
  {
    id: "Kha'Zix",
    name: "Kha'Zix",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Khazix_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Khazix.png",
    },
    roles: ["Selva"],
    tags: ["Assassino"],
    genre: "Masculino",
    specie: ["Ser Vazio"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Vazio"],
    release_year: 2012,
  },
  {
    id: "Kindred",
    name: "Kindred",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kindred_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Kindred.png",
    },
    roles: ["Selva"],
    tags: ["Atirador"],
    genre: "Outro",
    specie: ["Deus", "Espírito"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Runeterra"],
    release_year: 2015,
  },
  {
    id: "Kled",
    name: "Kled",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kled_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Kled.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Yordle"],
    resource: "Coragem",
    range_type: ["Corpo a Corpo"],
    regions: ["Noxus"],
    release_year: 2016,
  },
  {
    id: "Kog'Maw",
    name: "Kog'Maw",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/KogMaw_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/KogMaw.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador", "Mago"],
    genre: "Masculino",
    specie: ["Ser Vazio"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Vazio"],
    release_year: 2010,
  },
  {
    id: "K'Sante",
    name: "K'Sante",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/KSante_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/KSante.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Golem"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Shurima"],
    release_year: 2022,
  },
  {
    id: "LeBlanc",
    name: "LeBlanc",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leblanc_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Leblanc.png",
    },
    roles: ["Mid"],
    tags: ["Mago", "Assassino"],
    genre: "Feminino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Noxus"],
    release_year: 2010,
  },
  {
    id: "Lee Sin",
    name: "Lee Sin",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/LeeSin_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/LeeSin.png",
    },
    roles: ["Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Humano", "Espiritualista"],
    resource: "Energia",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2011,
  },
  {
    id: "Leona",
    name: "Leona",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leona_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Leona.png",
    },
    roles: ["Suporte"],
    tags: ["Tanque", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Aspecto"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Targon"],
    release_year: 2011,
  },
  {
    id: "Lillia",
    name: "Lillia",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lillia_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Lillia.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Mago", "Lutador"],
    genre: "Feminino",
    specie: ["Espírito"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2020,
  },
  {
    id: "Lissandra",
    name: "Lissandra",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lissandra_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Lissandra.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Feminino",
    specie: ["Humano", "Nascido do Gelo"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Freljord"],
    release_year: 2013,
  },
  {
    id: "Lucian",
    name: "Lucian",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lucian_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Lucian.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Demacia", "Ilha das Sombras"],
    release_year: 2013,
  },
  {
    id: "Lulu",
    name: "Lulu",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lulu_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Lulu.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Yordle"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Bandópolis"],
    release_year: 2012,
  },
  {
    id: "Lux",
    name: "Lux",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lux_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Lux.png",
    },
    roles: ["Mid"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Demacia"],
    release_year: 2010,
  },
  {
    id: "Malphite",
    name: "Malphite",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malphite_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Malphite.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Golem"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Ixtal", "Shurima"],
    release_year: 2009,
  },
  {
    id: "Malzahar",
    name: "Malzahar",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malzahar_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Malzahar.png",
    },
    roles: ["Mid"],
    tags: ["Mago", "Assassino"],
    genre: "Masculino",
    specie: ["Humano", "Ser Vazio"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Shurima", "Vazio"],
    release_year: 2010,
  },
  {
    id: "Maokai",
    name: "Maokai",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Maokai_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Maokai.png",
    },
    roles: ["Top", "Suporte"],
    tags: ["Tanque", "Mago"],
    genre: "Masculino",
    specie: ["Espírito"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Ilha das Sombras"],
    release_year: 2011,
  },
  {
    id: "Master Yi",
    name: "Master Yi",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MasterYi_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/MasterYi.png",
    },
    roles: ["Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Humano", "Espiritualista"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2009,
  },
  {
    id: "Miss Fortune",
    name: "Miss Fortune",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MissFortune_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/MissFortune.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Águas de Sentina"],
    release_year: 2010,
  },
  {
    id: "Mordekaiser",
    name: "Mordekaiser",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Mordekaiser_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Mordekaiser.png",
    },
    roles: ["Top"],
    tags: ["Lutador"],
    genre: "Masculino",
    specie: ["Fantasma"],
    resource: "Escudo",
    range_type: ["Corpo a Corpo"],
    regions: ["Noxus"],
    release_year: 2010,
  },
  {
    id: "Morgana",
    name: "Morgana",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Morgana_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Morgana.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Aspecto", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Demacia", "Targon"],
    release_year: 2009,
  },
  {
    id: "Nami",
    name: "Nami",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nami_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Nami.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Vastaya"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Runeterra"],
    release_year: 2012,
  },
  {
    id: "Nasus",
    name: "Nasus",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nasus_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Nasus.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Deus-Guerreiro"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Shurima"],
    release_year: 2009,
  },
  {
    id: "Nautilus",
    name: "Nautilus",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nautilus_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Nautilus.png",
    },
    roles: ["Suporte"],
    tags: ["Tanque", "Suporte"],
    genre: "Masculino",
    specie: ["Fantasma"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Águas de Sentina"],
    release_year: 2012,
  },
  {
    id: "Neeko",
    name: "Neeko",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Neeko_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Neeko.png",
    },
    roles: ["Mid", "Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Vastaya"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ixtal"],
    release_year: 2018,
  },
  {
    id: "Nidalee",
    name: "Nidalee",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nidalee_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Nidalee.png",
    },
    roles: ["Selva"],
    tags: ["Mago", "Assassino"],
    genre: "Feminino",
    specie: ["Humano", "Espiritualista"],
    resource: "Mana",
    range_type: ["Corpo a Corpo", "À distância"],
    regions: ["Ixtal"],
    release_year: 2009,
  },
  {
    id: "Nilah",
    name: "Nilah",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nilah_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Nilah.png",
    },
    roles: ["Atirador"],
    tags: ["Assassino", "Lutador"],
    genre: "Feminino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Águas de Sentina"],
    release_year: 2022,
  },
  {
    id: "Nocturne",
    name: "Nocturne",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nocturne_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Nocturne.png",
    },
    roles: ["Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Demônio", "Espírito"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Runeterra"],
    release_year: 2011,
  },
  {
    id: "Nunu",
    name: "Nunu",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nunu_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Nunu.png",
    },
    roles: ["Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano", "Yeti"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Freljord"],
    release_year: 2009,
  },
  {
    id: "Olaf",
    name: "Olaf",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Olaf_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Olaf.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano", "Nascido do Gelo"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Freljord"],
    release_year: 2010,
  },
  {
    id: "Orianna",
    name: "Orianna",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Orianna_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Orianna.png",
    },
    roles: ["Mid"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Golem"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Piltover"],
    release_year: 2011,
  },
  {
    id: "Ornn",
    name: "Ornn",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ornn_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Ornn.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Deus", "Espírito"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Freljord"],
    release_year: 2017,
  },
  {
    id: "Pantheon",
    name: "Pantheon",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pantheon_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Pantheon.png",
    },
    roles: ["Selva", "Mid", "Suporte"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Humano", "Aspecto"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Targon"],
    release_year: 2010,
  },
  {
    id: "Poppy",
    name: "Poppy",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Poppy.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Feminino",
    specie: ["Yordle"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Demacia"],
    release_year: 2010,
  },
  {
    id: "Pyke",
    name: "Pyke",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pyke_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Pyke.png",
    },
    roles: ["Suporte"],
    tags: ["Assassino", "Suporte"],
    genre: "Masculino",
    specie: ["Fantasma"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Águas de Sentina"],
    release_year: 2018,
  },
  {
    id: "Qiyana",
    name: "Qiyana",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Qiyana_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Qiyana.png",
    },
    roles: ["Mid", "Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Feminino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Ixtal"],
    release_year: 2019,
  },
  {
    id: "Quinn",
    name: "Quinn",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Quinn_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Quinn.png",
    },
    roles: ["Top"],
    tags: ["Atirador", "Assassino"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Demacia"],
    release_year: 2013,
  },
  {
    id: "Rakan",
    name: "Rakan",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rakan_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Rakan.png",
    },
    roles: ["Suporte"],
    tags: ["Suporte"],
    genre: "Masculino",
    specie: ["Vastaya"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2017,
  },
  {
    id: "Rammus",
    name: "Rammus",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rammus_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Rammus.png",
    },
    roles: ["Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Deus-Guerreiro"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Shurima"],
    release_year: 2009,
  },
  {
    id: "Rek'Sai",
    name: "Rek'Sai",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/RekSai_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/RekSai.png",
    },
    roles: ["Selva"],
    tags: ["Lutador"],
    genre: "Feminino",
    specie: ["Ser Vazio"],
    resource: "Fúria",
    range_type: ["Corpo a Corpo"],
    regions: ["Shurima", "Vazio"],
    release_year: 2014,
  },
  {
    id: "Rell",
    name: "Rell",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rell_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Rell.png",
    },
    roles: ["Suporte"],
    tags: ["Tanque", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Magicamente Alterado", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Noxus"],
    release_year: 2020,
  },
  {
    id: "Renata Glasc",
    name: "Renata Glasc",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renata_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Renata.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Quimicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Zaun"],
    release_year: 2022,
  },
  {
    id: "Renekton",
    name: "Renekton",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renekton_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Renekton.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Deus-Guerreiro"],
    resource: "Fúria",
    range_type: ["Corpo a Corpo"],
    regions: ["Shurima"],
    release_year: 2011,
  },
  {
    id: "Rengar",
    name: "Rengar",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rengar_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Rengar.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Vastaya"],
    resource: "Ferocidade",
    range_type: ["Corpo a Corpo"],
    regions: ["Ixtal", "Shurima"],
    release_year: 2012,
  },
  {
    id: "Riven",
    name: "Riven",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Riven_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Riven.png",
    },
    roles: ["Top"],
    tags: ["Assassino", "Lutador"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Nenhum",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia", "Noxus"],
    release_year: 2011,
  },
  {
    id: "Rumble",
    name: "Rumble",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rumble_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Rumble.png",
    },
    roles: ["Mid", "Top"],
    tags: ["Mago", "Lutador"],
    genre: "Masculino",
    specie: ["Yordle"],
    resource: "Aquecimento",
    range_type: ["Corpo a Corpo"],
    regions: ["Bandópolis"],
    release_year: 2011,
  },
  {
    id: "Ryze",
    name: "Ryze",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ryze_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Ryze.png",
    },
    roles: ["Mid", "Top"],
    tags: ["Mago", "Lutador"],
    genre: "Masculino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Runeterra"],
    release_year: 2009,
  },
  {
    id: "Samira",
    name: "Samira",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Samira_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Samira.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Noxus", "Shurima"],
    release_year: 2020,
  },
  {
    id: "Sejuani",
    name: "Sejuani",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sejuani_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Sejuani.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Feminino",
    specie: ["Humano", "Nascido do Gelo"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Freljord"],
    release_year: 2012,
  },
  {
    id: "Senna",
    name: "Senna",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Senna_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Senna.png",
    },
    roles: ["Suporte"],
    tags: ["Atirador", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Morto-Vivo"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ilha das Sombras"],
    release_year: 2019,
  },
  {
    id: "Seraphine",
    name: "Seraphine",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Seraphine_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Seraphine.png",
    },
    roles: ["Mid", "Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Piltover", "Zaun"],
    release_year: 2020,
  },
  {
    id: "Sett",
    name: "Sett",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sett_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Sett.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano", "Vastaya"],
    resource: "Ousadia",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2020,
  },
  {
    id: "Shaco",
    name: "Shaco",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shaco_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Shaco.png",
    },
    roles: ["Selva"],
    tags: ["Assassino"],
    genre: "Masculino",
    specie: ["Espírito"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Runeterra"],
    release_year: 2009,
  },
  {
    id: "Shen",
    name: "Shen",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shen_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Shen.png",
    },
    roles: ["Top"],
    tags: ["Tanque"],
    genre: "Masculino",
    specie: ["Humano", "Espiritualista"],
    resource: "Energia",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2010,
  },
  {
    id: "Shyvana",
    name: "Shyvana",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shyvana_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Shyvana.png",
    },
    roles: ["Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Feminino",
    specie: ["Dragão", "Magicamente Alterado"],
    resource: "Fúria",
    range_type: ["Corpo a Corpo"],
    regions: ["Demacia"],
    release_year: 2011,
  },
  {
    id: "Singed",
    name: "Singed",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Singed_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Singed.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano", "Quimicamente Alterado"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Piltover", "Zaun"],
    release_year: 2009,
  },
  {
    id: "Sion",
    name: "Sion",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sion_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Sion.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Fantasma"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Noxus"],
    release_year: 2009,
  },
  {
    id: "Sivir",
    name: "Sivir",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sivir_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Sivir.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Shurima"],
    release_year: 2009,
  },
  {
    id: "Skarner",
    name: "Skarner",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Skarner_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Skarner.png",
    },
    roles: ["Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Brackern"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Shurima"],
    release_year: 2011,
  },
  {
    id: "Sona",
    name: "Sona",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sona_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Sona.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Demacia", "Ionia"],
    release_year: 2010,
  },
  {
    id: "Soraka",
    name: "Soraka",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Soraka_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Soraka.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Celestial"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ionia", "Targon"],
    release_year: 2009,
  },
  {
    id: "Swain",
    name: "Swain",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Swain_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Swain.png",
    },
    roles: ["Mid", "Suporte"],
    tags: ["Mago", "Lutador"],
    genre: "Masculino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Noxus"],
    release_year: 2010,
  },
  {
    id: "Sylas",
    name: "Sylas",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sylas_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Sylas.png",
    },
    roles: ["Mid"],
    tags: ["Mago", "Assassino"],
    genre: "Masculino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Demacia", "Freljord"],
    release_year: 2019,
  },
  {
    id: "Syndra",
    name: "Syndra",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Syndra_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Syndra.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Feminino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ionia"],
    release_year: 2012,
  },
  {
    id: "Tahm Kench",
    name: "Tham Kench",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/TahmKench_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/TahmKench.png",
    },
    roles: ["Top", "Suporte"],
    tags: ["Tanque", "Suporte"],
    genre: "Masculino",
    specie: ["Demônio", "Espírito"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Águas de Sentina", "Runeterra"],
    release_year: 2015,
  },
  {
    id: "Taliyah",
    name: "Taliyah",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Taliyah_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Taliyah.png",
    },
    roles: ["Mid", "Selva"],
    tags: ["Mago"],
    genre: "Feminino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Shurima"],
    release_year: 2016,
  },
  {
    id: "Talon",
    name: "Talon",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Talon_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Talon.png",
    },
    roles: ["Mid", "Selva"],
    tags: ["Assassino"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Noxus"],
    release_year: 2011,
  },
  {
    id: "Taric",
    name: "Taric",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Taric_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Taric.png",
    },
    roles: ["Suporte"],
    tags: ["Lutador", "Suporte"],
    genre: "Masculino",
    specie: ["Humano", "Aspecto"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Demacia", "Targon"],
    release_year: 2009,
  },
  {
    id: "Teemo",
    name: "Teemo",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Teemo_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Teemo.png",
    },
    roles: ["Top"],
    tags: ["Atirador", "Assassino"],
    genre: "Masculino",
    specie: ["Yordle"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Bandópolis"],
    release_year: 2009,
  },
  {
    id: "Thresh",
    name: "Thresh",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Thresh_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Thresh.png",
    },
    roles: ["Suporte"],
    tags: ["Lutador", "Suporte"],
    genre: "Masculino",
    specie: ["Morto-Vivo"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ilha das Sombras"],
    release_year: 2013,
  },
  {
    id: "Tristana",
    name: "Tristana",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tristana_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Tristana.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Feminino",
    specie: ["Yordle"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Bandópolis"],
    release_year: 2009,
  },
  {
    id: "Trundle",
    name: "Trundle",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Trundle_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Trundle.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Troll", "Nascido do Gelo"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Freljord"],
    release_year: 2010,
  },
  {
    id: "Tryndamere",
    name: "Tryndamere",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tryndamere_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Tryndamere.png",
    },
    roles: ["Top"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Fúria",
    range_type: ["Corpo a Corpo"],
    regions: ["Freljord"],
    release_year: 2009,
  },
  {
    id: "Twisted Fate",
    name: "Twisted Fate",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/TwistedFate_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/TwistedFate.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Masculino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Águas de Sentina"],
    release_year: 2009,
  },
  {
    id: "Twitch",
    name: "Twitch",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Twitch_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Twitch.png",
    },
    roles: ["Atirador", "Selva"],
    tags: ["Atirador", "Assassino"],
    genre: "Masculino",
    specie: ["Rato", "Quimicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Zaun"],
    release_year: 2009,
  },
  {
    id: "Udyr",
    name: "Udyr",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Udyr_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Udyr.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano", "Espiritualista"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Freljord", "Ionia"],
    release_year: 2009,
  },
  {
    id: "Urgot",
    name: "Urgot",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Urgot_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Urgot.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano", "Quimicamente Alterado", "Ciborgue"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Noxus", "Zaun"],
    release_year: 2010,
  },
  {
    id: "Varus",
    name: "Varus",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Varus_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Varus.png",
    },
    roles: ["Mid", "Top"],
    tags: ["Atirador", "Mago"],
    genre: "Masculino",
    specie: ["Humano", "Darkin"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ionia", "Runeterra", "Shurima"],
    release_year: 2012,
  },
  {
    id: "Vayne",
    name: "Vayne",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vayne_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Vayne.png",
    },
    roles: ["Atirador", "Top"],
    tags: ["Atirador", "Assassino"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Demacia"],
    release_year: 2011,
  },
  {
    id: "Veigar",
    name: "Veigar",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Veigar_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Veigar.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Masculino",
    specie: ["Yordle"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Bandópolis", "Runeterra"],
    release_year: 2009,
  },
  {
    id: "Vel'Koz",
    name: "Vel'Koz",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Velkoz_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Velkoz.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Masculino",
    specie: ["Ser Vazio"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Vazio"],
    release_year: 2014,
  },
  {
    id: "Vex",
    name: "Vex",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vex_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Vex.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Feminino",
    specie: ["Yordle"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Bandópolis", "Ilha das Sombras"],
    release_year: 2021,
  },
  {
    id: "Vi",
    name: "Vi",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vi_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Vi.png",
    },
    roles: ["Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Feminino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Piltover", "Zaun"],
    release_year: 2012,
  },
  {
    id: "Viego",
    name: "Viego",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viego_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Viego.png",
    },
    roles: ["Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Morto-Vivo"],
    resource: "Nenhum",
    range_type: ["Corpo a Corpo"],
    regions: ["Camaveia", "Ilha das Sombras"],
    release_year: 2021,
  },
  {
    id: "Viktor",
    name: "Viktor",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viktor_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Viktor.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Masculino",
    specie: ["Humano", "Ciborgue"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Piltover", "Zaun"],
    release_year: 2011,
  },
  {
    id: "Vladimir",
    name: "Vladimir",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vladimir_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Vladimir.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Masculino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Sede de Sangue",
    range_type: ["À distância"],
    regions: ["Camaveia", "Noxus", "Ilha das Sombras"],
    release_year: 2010,
  },
  {
    id: "Volibear",
    name: "Volibear",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Volibear_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Volibear.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Deus", "Espírito"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Freljord"],
    release_year: 2011,
  },
  {
    id: "Warwick",
    name: "Warwick",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Warwick_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Warwick.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano", "Quimicamente Alterado", "Ciborgue"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Zaun"],
    release_year: 2009,
  },
  {
    id: "Wukong",
    name: "Wukong",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MonkeyKing_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/MonkeyKing.png",
    },
    roles: ["Top", "Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Vastaya"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2011,
  },
  {
    id: "Xayah",
    name: "Xayah",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xayah_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Xayah.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Feminino",
    specie: ["Vastaya"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ionia"],
    release_year: 2017,
  },
  {
    id: "Xerath",
    name: "Xerath",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xerath_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Xerath.png",
    },
    roles: ["Mid"],
    tags: ["Mago"],
    genre: "Masculino",
    specie: ["Deus-Guerreiro"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Shurima"],
    release_year: 2011,
  },
  {
    id: "Xin Zhao",
    name: "Xin Zhao",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/XinZhao_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/XinZhao.png",
    },
    roles: ["Selva"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Humano"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Demacia", "Ionia", "Noxus"],
    release_year: 2010,
  },
  {
    id: "Yasuo",
    name: "Yasuo",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yasuo_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Yasuo.png",
    },
    roles: ["Mid"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Fluxo",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2013,
  },
  {
    id: "Yone",
    name: "Yone",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yone_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Yone.png",
    },
    roles: ["Mid", "Top"],
    tags: ["Assassino", "Lutador"],
    genre: "Masculino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Nenhum",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2020,
  },
  {
    id: "Yorick",
    name: "Yorick",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yorick_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Yorick.png",
    },
    roles: ["Top"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["Corpo a Corpo"],
    regions: ["Ilha das Sombras"],
    release_year: 2011,
  },
  {
    id: "Yuumi",
    name: "Yuumi",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yuumi_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Yuumi.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Gato", "Magicamente Alterado"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Bandópolis"],
    release_year: 2019,
  },
  {
    id: "Zac",
    name: "Zac",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zac_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Zac.png",
    },
    roles: ["Selva"],
    tags: ["Lutador", "Tanque"],
    genre: "Masculino",
    specie: ["Golem"],
    resource: "Vida",
    range_type: ["Corpo a Corpo"],
    regions: ["Zaun"],
    release_year: 2013,
  },
  {
    id: "Zed",
    name: "Zed",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zed_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Zed.png",
    },
    roles: ["Mid"],
    tags: ["Assassino"],
    genre: "Masculino",
    specie: ["Humano", "Magicamente Alterado"],
    resource: "Energia",
    range_type: ["Corpo a Corpo"],
    regions: ["Ionia"],
    release_year: 2012,
  },
  {
    id: "Zeri",
    name: "Zeri",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zeri_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Zeri.png",
    },
    roles: ["Atirador"],
    tags: ["Atirador"],
    genre: "Feminino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Zaun"],
    release_year: 2022,
  },
  {
    id: "Ziggs",
    name: "Ziggs",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ziggs_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Ziggs.png",
    },
    roles: ["Mid", "Atirador"],
    tags: ["Mago"],
    genre: "Masculino",
    specie: ["Yordle"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Piltover", "Zaun"],
    release_year: 2012,
  },
  {
    id: "Zilean",
    name: "Zilean",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zilean_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Zilean.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Masculino",
    specie: ["Humano", "Nascido da Magia"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Icathia", "Runeterra", "Shurima"],
    release_year: 2009,
  },
  {
    id: "Zoe",
    name: "Zoe",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zoe_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Zoe.png",
    },
    roles: ["Mid"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Humano", "Aspecto"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Targon"],
    release_year: 2017,
  },
  {
    id: "Zyra",
    name: "Zyra",
    image: {
      full: "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zyra_0.jpg",
      sprite:
        "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Zyra.png",
    },
    roles: ["Suporte"],
    tags: ["Mago", "Suporte"],
    genre: "Feminino",
    specie: ["Desconhecido"],
    resource: "Mana",
    range_type: ["À distância"],
    regions: ["Ixtal"],
    release_year: 2012,
  },
];
